### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by ziphyfyi** [Gurkengewuerz/KShare#18]
I click on the download, login, than I get a 404.

**Comment by Gurkengewuerz** [comment]
What link do you try to click? You can download the current artifacts at https://artifacts.mc8051.de/Gurkengewuerz/KShare/

**Comment by Gurkengewuerz** [comment]
Oh i See, i didn't updated the table in the readme. Will do it tomorrow, but as i said the build artifacts are availaible at the link above
