### ISSUE TITLE
Qt 5.12 Error Upon Running KShare

### ISSUE THREAD

**Issue by ThoshHub** [Gurkengewuerz/KShare#21]
I am using Ubuntu 18.04 and I get the following error:
```
kshare: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by kshare)
```
Any ideas on how to fix it?
Is there anyway to install Qt 5.12? I currently have Qt 5.9.5 installed according to the command qtdiag:

```
Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.4.0) on "xcb" 
OS: Ubuntu 18.04.5 LTS [linux version 5.4.0-47-generic]
```

**Comment by Gurkengewuerz** [comment]
The QT version for Debian/Ubuntu is way to outdated. Please use the offical releases by QT. Please use the [QT-wiki](https://wiki.qt.io/Install_Qt_5_on_Ubuntu) to see how to install it.

**Comment by ThoshHub** [comment]
I installed qt 5.12.9 and I still get the same error
![image](https://user-images.githubusercontent.com/24558466/93877057-d44f6d80-fca5-11ea-9396-004add38d0d3.png)
Any ideas?

**Comment by ThoshHub** [comment]
Actually I tried this:
```
export LD_LIBRARY_PATH=/opt/Qt5.12.9/5.12.9/gcc_64/lib
```
and then running 
```
kshare
```
and it works! 
is there anyway to make this permanent? for example if I am not running from the command line

**Comment by Gurkengewuerz** [comment]
you forgot to add/update LD_LIBRARY_PATH in your environment variable. Please google how to set the enviroment variables permanently for your distribution.

**Comment by ThoshHub** [comment]
Thanks
