### ISSUE TITLE
Capture toolbar icons blank

### ISSUE THREAD

**Issue by Notexe** [Gurkengewuerz/KShare#7]
![image](https://user-images.githubusercontent.com/43296291/79329679-8fd3df00-7f5b-11ea-9372-e828f8c986c4.png)
Running on Arch Linux with this package https://aur.archlinux.org/packages/kshare
No errors/warnings appearing in terminal output.

**Comment by Notexe** [comment]
Nevermind, only seems to be an issue when using Kvantum for Qt theming.

**Comment by Gurkengewuerz** [comment]
Thanks for your feedback!
This would also suprise me if it were an arch related issue. I am using KShare on arch and it runs like a charm :)

So i think this issue can be closed
