### ISSUE TITLE
each screenshot creates a new playback stream

### ISSUE THREAD

**Issue by eEQK** [Gurkengewuerz/KShare#8]
Recently I've updated to a new version of kshare. It looks cool but as stated in the title, a new playback stream is being created with each screenshot. They are gone once you close the app.

![image](https://user-images.githubusercontent.com/15970653/80995368-71685180-8e3e-11ea-8eb5-29e16cd28521.png)

I'm running manjaro with latest linux 5.6. Kshare 5.0.3

**Comment by Gurkengewuerz** [comment]
Hey @mightybruno. ACK. Thanks for the issue! I didn't notice that and i agree that this should be fixed. 
Unfortunately I am very busy at the moment and cannot tell you when I will be able to find freetime.

**Comment by Gurkengewuerz** [comment]
_Whoops! Wrong button! The closing of the issue was accidentally. 😅🙃🙃_
